#ifndef __OPEN_EEPROM_CONF_H__
#define __OPEN_EEPROM_CONF_H__

#include "open-eeprom.h"

#define OPEN_EEPROM_VERSION_NUMBER        0x01
#define OPEN_EEPROM_SUPPORTED_BUS_TYPES   OPEN_EEPROM_BUS_MODE_PARALLEL | OPEN_EEPROM_BUS_MODE_SPI;  


#endif /* __OPEN_EEPROM_CONF_H__ */

